version: '2'
services:
  database:
    container_name: dhis2-database
    # image: mdillon/postgis:9.6
    image: intellisoftkenya/beninmrs:1.0
    command: postgres -c max_locks_per_transaction=100
    # volumes: 
    # - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB_TARGET: dhis-target
      PG_DATA: /var/lib/postgresql/data/pgdata:z
    ports:
     - "5432:5432"
  web:
    container_name: dhis2-web
    image: dhis2/dhis2-web:2.29-tomcat7-jre8-latest
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m"
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "8085:8080"
    depends_on:
      - database
    entrypoint: ./wait-for-it.sh -t 0 database:5432 --
    command: catalina.sh run # https://github.com/docker/compose/issues/3140
